### ISSUE TITLE
Are there any color controls available?

### ISSUE THREAD

**Issue by hsauro** [Embarcadero/DelphiFMX4Python#9] opened 2022-01-30 05:30 UTC
I tried using the ColorComboBox but noticed its not wrapped. Are there any color selectors we can use with delphifmx?

**Comment by lmbelo** [comment] 2022-01-31 13:48
@hsauro I'm releasing a new version that includes the ColorComboBox.

**Comment by lmbelo** [comment] 2022-01-31 16:25
I have released the FMX.Colors unit components, but only its types, not special methods or custom events. Can you try it, please?

**Comment by hsauro** [comment] 2022-01-31 16:39
Ok I will, I’ll get back to you in a day or two.

**Comment by hsauro** [comment] 2022-02-01 00:32
I just had an opportunity to try it out. I'm not sure if it is an issue at my or not but the following gives the error:

If a color is selected and the OnChange fires, the extraction of the color value yields the error AttributeError: Error in getting property 'Color', Error: Overflow while converting variant of type (Cardinal) into type (integer). I'm running this on Python 64 bit. 

          import os                                                                                              
          from delphifmx import *                                                                                
                                                                                                                 
          class Form3(Form):                                                                        
              def __init__(self, owner): 
                  self.ColorBox = ColorComboBox(self)                                                                        
                  self.ColorBox.SetProps (Parent=self, OnChange=self.__Color_OnChange)                                                                          
          
              def __Color_OnChange (self, sender):
    	          mycolor = self.ColorBox.Color
          
          
          def main():                                                                                            
              Application.Initialize()                                                                           
              Application.Title = 'Main'                                                                     
              Application.MainForm = Form3(Application)                                                     
              Application.MainForm.Show()                                                                        
              Application.Run()                                                                                  
              Application.MainForm.Destroy()                                                                     
                                                                                                                 
          if __name__ == '__main__':                                                                           
              main()

**Comment by lmbelo** [comment] 2022-02-01 12:16
@hsauro I'm still working on events.

**Comment by hsauro** [comment] 2022-02-01 16:42
The event works, but I can’t read the color property.

**Comment by lmbelo** [comment] 2022-02-02 12:56
@hsauro I'll try to figure out.

**Comment by hsauro** [comment] 2022-02-12 04:49
I wonder if the error I'm seeing to extracting the color value is related to this:

https://quality.embarcadero.com/browse/RSP-18363

"Error: Overflow while converting variant of type (Cardinal) into type (integer)."

**Comment by lmbelo** [comment] 2022-02-12 15:37
@hsauro we are revisiting wrapped events and including what is still missing.
I'm considering this bug in the roadmap and I hope to get it back shortly.

**Comment by lmbelo** [comment] 2022-02-15 00:45
@hsauro I had a chance to reproduce this issue.
We are currently working on a workaround.
Thank you for the valuable information.

**Comment by lmbelo** [comment] 2022-02-15 21:35
![image](https://user-images.githubusercontent.com/8376898/154153128-fd55603e-548f-4436-8039-36f4acee8244.png)

It is not a bug, it is a feature. I have a workaround. It will be available on our next release.

**Comment by hsauro** [comment] 2022-02-15 23:48
Thanks for investigating this, I look forward to the next release.

**Comment by lmbelo** [comment] 2022-02-24 17:57
@hsauro we released a patch to the error you've mention here. Please, let me know if it worked for you.

**Comment by hsauro** [comment] 2022-02-25 04:21
Ok thanks, I’ll try it at the weekend.

**Comment by lmbelo** [comment] 2022-03-06 17:13
@hsauro have you tried it? Let me know when we can close this issue.

**Comment by hsauro** [comment] 2022-03-07 01:29
I tried today. I can retrieve colors using ComboColorBox.Color.  I can also set colors but one has to remember to use the signed 2's compliment. Eg Tomato is -40121 in decimal but xFFFF6347 in signed 2's complement. I think this issue can be closed now. Thanks for getting this working I can now continue with the project I was working on.

**Comment by lmbelo** [comment] 2022-03-07 20:25
@hsauro negative decimal values should work as well.

**Comment by hsauro** [comment] 2022-03-07 23:46
Correct, that's how I discovered I could use the compliment.

**Closed** 2022-03-08 10:46 UTC
Labels: enhancement
